.PHONY: clean All

All:
	@echo "----------Building project:[ Longest_Palindromic_Substring - Debug ]----------"
	@cd "Longest_Palindromic_Substring" && "$(MAKE)" -f  "Longest_Palindromic_Substring.mk"
clean:
	@echo "----------Cleaning project:[ Longest_Palindromic_Substring - Debug ]----------"
	@cd "Longest_Palindromic_Substring" && "$(MAKE)" -f  "Longest_Palindromic_Substring.mk" clean
